[styling.palette]
bg = "#101418"
surface = "#101418"
elevated = "#272a2f"
fg = "#e0e2e8"
fg-muted = "#c2c7cf"
primary = "#9bcbfb"
red = "#E78284"
yellow = "#E5C890"
green = "#A6D189"
blue = "#8CAAEE"
