# Généré par matugen — ne pas éditer à la main.
$background          = rgba(0e1513ff)
$surface            = rgba(1b211fff)
$surface_high       = rgba(252b29ff)
$primary            = rgba(86d6bfff)
$on_primary         = rgba(00382dff)
$on_surface         = rgba(dee4e0ff)
$on_surface_variant = rgba(bfc9c4ff)
$outline            = rgba(89938fff)
$error              = rgba(ffb4abff)
