-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            size = 7,
        },
        inactive_opacity = 0.75,
        rounding = 16,
        shadow = {
            range = 32,
            render_power = 2,
        },
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(cba6f7ff)", "rgba(89b4faff)"},
                angle = 55,
            },
            inactive_border = {
                colors = {"rgba(6c7086ff)"},
                angle = 10,
            },
        },
        gaps_in = 6,
        gaps_out = 14,
        snap = {
            enabled = true,
        },
    },
    misc = {
        disable_splash_rendering = true,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = true,
})
