# Gestion de l'inactivité (hypridle)

general {
    lock_cmd = pidof hyprlock || hyprlock       # évite les instances multiples
    before_sleep_cmd = loginctl lock-session    # verrouille avant mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # rallume l'écran au réveil
}

# Verrouillage après 15 min d'inactivité (l'écran reste allumé)
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}
